#SESSION_0_TYPE=blackbox
#SESSION_0_AUTOSTART=on

AUDIO_LEVEL=67
KEYBOARD_MAP=en_us
TIME_ZONE="UTC-12:30"
SYSLOG_SERVER=local
USB_ENABLED=On
USB_STORAGE_SYNC=On
USB_MOUNT_DIR="/mnt/usbdevice"
USB_MOUNT_USELABEL="Yes"
USB_MOUNT_OPTIONS="utf8,shortname=win95"
DAILY_REBOOT=On
#AUTOPLAYCD=On
CUSTOM_CONFIG=Off
RECONNECT_PROMPT=On

SCREEN_RESOLUTION="1024x768"
SCREEN_COLOR_DEPTH="16"

SESSION_0_TYPE=icewm
SESSION_0_AUTOSTART=on
