#SESSION_0_TYPE=blackbox icewm
#SESSION_0_AUTOSTART=on

AUDIO_LEVEL=70
KEYBOARD_MAP=en_us
TIME_ZONE="UTC-12:30"
SYSLOG_SERVER=local
USB_ENABLED=On
USB_STORAGE_SYNC=On
USB_MOUNT_DIR="/mnt/usbdevice"
USB_MOUNT_USELABEL="Yes"
USB_MOUNT_OPTIONS="utf8,shortname=win95"
DAILY_REBOOT=On
#AUTOPLAYCD=On
CUSTOM_CONFIG=Off
RECONNECT_PROMPT=On

SCREEN_RESOLUTION="1024x768"
SCREEN_COLOR_DEPTH="16"

SESSION_0_TITLE="ICE"
SESSION_0_TYPE=icewm
SESSION_0_SCREEN=1
SESSION_0_AUTOSTART=on

# SESSION_1_TITLE="BLACK"
# SESSION_1_TYPE=blackbox
# SESSION_1_SCREEN=1
# SESSION_1_AUTOSTART=off
# 
# 
# SESSION_2_TITLE="RDP"
# SESSION_2_TYPE=rdesktop
# SESSION_2_SCREEN=1
# SESSION_2_SCREEN_POSITION=2
# SESSION_2_RDESKTOP_SERVER=192.168.3.136
# SESSION_2_RDESKTOP_OPTIONS="-r sound:local -f -u ning -a 16"
# SESSION_2_AUTOSTART=Off

# SESSION_1_TITLE="SSH"
# SESSION_1_TYPE=ssh
# SESSION_1_SSH_SERVER=127.0.0.1